import { ExamPreset } from './types';

export const PRESETS: ExamPreset[] = [
  {
    id: 'upsc-photo',
    name: 'UPSC Photo',
    nameHi: 'UPSC फोटो',
    category: 'upsc',
    kind: 'photo',
    targetWidth: 413,
    targetHeight: 531,
    minKb: 20,
    maxKb: 300,
    description: '413 x 531 px, 20 KB - 300 KB (Civil Services, NDA, CDS)',
    descriptionHi: '413 x 531 px, 20 KB - 300 KB (सिविल सेवा, NDA, CDS)',
    defaultFilename: 'upsc-photo.jpg',
    isPopular: true,
  },
  {
    id: 'upsc-signature',
    name: 'UPSC Signature',
    nameHi: 'UPSC हस्ताक्षर',
    category: 'upsc',
    kind: 'signature',
    targetWidth: 140,
    targetHeight: 60,
    minKb: 20,
    maxKb: 300,
    description: '140 x 60 px, 20 KB - 300 KB (Black ink on white paper)',
    descriptionHi: '140 x 60 px, 20 KB - 300 KB (सफेद कागज पर काली स्याही)',
    defaultFilename: 'upsc-signature.jpg',
    isPopular: true,
  },
  {
    id: 'ssc-photo',
    name: 'SSC Photo',
    nameHi: 'SSC फोटो',
    category: 'ssc',
    kind: 'photo',
    targetWidth: 100,
    targetHeight: 120,
    minKb: 20,
    maxKb: 50,
    description: '100 x 120 px, 20 KB - 50 KB (CGL, CHSL, MTS, GD)',
    descriptionHi: '100 x 120 px, 20 KB - 50 KB (CGL, CHSL, MTS, GD)',
    defaultFilename: 'ssc-photo.jpg',
  },
  {
    id: 'ssc-signature',
    name: 'SSC Signature',
    nameHi: 'SSC हस्ताक्षर',
    category: 'ssc',
    kind: 'signature',
    targetWidth: 140,
    targetHeight: 60,
    minKb: 10,
    maxKb: 20,
    description: '140 x 60 px, 10 KB - 20 KB (Black/Blue ink)',
    descriptionHi: '140 x 60 px, 10 KB - 20 KB (काली/नीली स्याही)',
    defaultFilename: 'ssc-signature.jpg',
  },
  {
    id: 'ibps-photo',
    name: 'IBPS / Bank Photo',
    nameHi: 'IBPS / बैंक फोटो',
    category: 'ibps',
    kind: 'photo',
    targetWidth: 200,
    targetHeight: 230,
    minKb: 20,
    maxKb: 50,
    description: '200 x 230 px, 20 KB - 50 KB (PO, Clerk, SO, RRB)',
    descriptionHi: '200 x 230 px, 20 KB - 50 KB (PO, क्लर्क, SO, RRB)',
    defaultFilename: 'ibps-photo.jpg',
  },
  {
    id: 'ibps-signature',
    name: 'IBPS Signature',
    nameHi: 'IBPS हस्ताक्षर',
    category: 'ibps',
    kind: 'signature',
    targetWidth: 140,
    targetHeight: 60,
    minKb: 10,
    maxKb: 20,
    description: '140 x 60 px, 10 KB - 20 KB (White background)',
    descriptionHi: '140 x 60 px, 10 KB - 20 KB (सफेद पृष्ठभूमि)',
    defaultFilename: 'ibps-signature.jpg',
  },
  {
    id: 'custom',
    name: 'Custom Size',
    nameHi: 'कस्टम आकार',
    category: 'custom',
    kind: 'custom',
    targetWidth: 350,
    targetHeight: 350,
    minKb: 20,
    maxKb: 100,
    description: 'Set your own width, height and target file size',
    descriptionHi: 'अपनी चौड़ाई, ऊंचाई और लक्षित फ़ाइल आकार सेट करें',
    defaultFilename: 'custom-resized.jpg',
  },
];
